### ISSUE TITLE
Capire come creare il github.io

### ISSUE THREAD

**Issue by EddyPinarello** [Code7Crusaders/docs#20]

**Comment by CcEnrico** [comment]
ho creato il sito utilizzando jekyll (strumento in ruby per build di siti statici automatica) che supposta bene github pages, il sito è sulla [repo dell'organizzazione](https://github.com/Code7Crusaders/code7crusaders.github.io) e il sito in esso è presente a questo link: [sito](https://code7crusaders.github.io/)

**Comment by CcEnrico** [comment]
> ho creato il sito utilizzando jekyll (strumento in ruby per build di siti statici automatica) che supposta bene github pages, il sito è sulla [repo dell'organizzazione](https://github.com/Code7Crusaders/code7crusaders.github.io) e il sito in esso è presente a questo link: [sito](https://code7crusaders.github.io/)

inoltre ci sono le istruzioni su come buildare e deployare il sito in locale per fare test senza rompere quello attualmente in uso

**Comment by CcEnrico** [comment]
Terminato sito iniziale presente a [code7crusader](https://code7crusaders.github.io/) .
