### ISSUE TITLE
verbale interno 4 novembre

### ISSUE THREAD

**Issue by CcEnrico** [Code7Crusaders/docs#25]
stesura verbale 4 novembre, cosa si è detto, scelte fatte e discussioni sulle decisioni prese, scrivere bene motivazioni delle tali

**Comment by CcEnrico** [comment]
> stesura verbale 4 novembre, cosa si è detto, scelte fatte e discussioni sulle decisioni prese, scrivere bene motivazioni delle tali

in particolare commentare perchè abbiamo preso la decisione di automatizzare e migliorare la scrittura con latex piuttosto che proseguire con typist.

**Comment by SerpenTaki** [comment]
Il documento è finito ma va ovviamente revisionato ulteriormente passandolo a v1.0
