### ISSUE TITLE
Rendicontazione ore

### ISSUE THREAD

**Issue by CcEnrico** [Code7Crusaders/docs#38]
Per Migliorare in nostro way of working facciamo un' automatismo per tenere conto del nostro monte ore automaticamente.

**Comment by francesco-lapenna** [comment]
# Rendicontazione Automatica Ore
Due soluzioni trovate

## Soluzione 1 (semiautomatica, peggiore)
- aggiungere un campo ore effettive ad ogni Project che creiamo
    - esempio:
      - nel Project "Documentazione C7C" al momento abbiamo i campi status, priority, size . . . end date
      - aggiungiamo il campo ore effettive (necessarie al completamento della issue)
      - creiamo una nuova vista che ci permette di vedere le ore svolte da ciascuno
### PRO
- semplice da fare
### CONTRO
- nel momento in cui apriamo altri Projects, ognuno avrà il proprio conteggio ore. Quindi per contare le mie ore totali dovrò aprire tutti i projects e fare la somma
- se vogliamo vedere non solo le ore totali svolte da ciascuno, ma anche le ore svolte da ciascuno per ruolo (secondo me non necessario), dovremmo aggiungere troppi campi e incasinare troppo


## Soluzione 2 (automatica, migliore)
- creare un nuovo Project "Conteggio Ore"
- linkarlo ad ogni issue creata dall'aggiudicazione dell'appalto alla fine del corso
- quando chiudiamo una issue compiliamo i suoi campi segnando le ore effettive svolte
### Varianti
Possiamo scegliere di contare solo le ore totali (+ semplice, - accurato) o di contare le ore per ruolo (- semplice, + accurato).
### PRO
- accurato e automatico
- conta tutte le ore del corso
### CONTRO
- bisogna ricordarsi di linkarlo ad ogni issue
- è un project a parte
